version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  AfterInstall:
    - location: scripts/install_python_dependencies.sh
      timeout: 6000
      runas: ubuntu
    - location: scripts/app_migrate_collectstatic.sh
      timeout: 18000
      runas: ubuntu
    - location: scripts/start_server.sh
      timeout: 6000
      runas: ubuntu
    - location: scripts/setup_env.sh
      timeout: 6000
      runas: ubuntu
