# Generated by Django 3.1.5 on 2021-09-16 16:36

from django.db import migrations, models
import feed.validators


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='track',
            field=models.FileField(upload_to='path/to/audio', validators=[feed.validators.file_size]),
        ),
    ]
