# Generated by Django 3.1.5 on 2021-02-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='musician',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
