# Generated by Django 3.1.5 on 2021-09-16 17:18

from django.db import migrations, models
import feed.validators


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210916_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artwork',
            field=models.ImageField(upload_to='path/to/img', validators=[feed.validators.file_size]),
        ),
    ]
