# Generated by Django 3.1.5 on 2021-02-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210205_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio',
        ),
    ]
