# Generated by Django 3.1.5 on 2021-02-17 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
