# Generated by Django 3.1.5 on 2021-04-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_music_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artist_name',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
