# Generated by Django 3.1.5 on 2021-04-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_music_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artwork',
            field=models.ImageField(upload_to='path/to/img'),
        ),
    ]
