# Generated by Django 3.1.5 on 2021-04-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20210412_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist_name',
            field=models.TextField(max_length=50),
        ),
    ]
