# Generated by Django 3.1.5 on 2021-04-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_auto_20210413_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artwork',
            field=models.ImageField(blank=True, upload_to='path/to/img'),
        ),
    ]
