# Generated by Django 3.1.5 on 2021-04-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_auto_20210413_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artwork',
            field=models.ImageField(blank=True, default='media/path/to/img/18784_qodTDVM.png', upload_to='path/to/img'),
        ),
    ]
