# Generated by Django 3.1.5 on 2021-04-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0016_auto_20210413_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artwork',
            field=models.ImageField(blank=True, default='http://127.0.0.1:8000/media/path/to/img/04007_autumnsunlightthroughthetrees_1920x1080_Uf05V9N.jpg', upload_to='path/to/img'),
        ),
    ]
