# Generated by Django 3.1.5 on 2021-04-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_auto_20210413_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='track',
            field=models.FileField(upload_to=''),
        ),
    ]
