# Generated by Django 3.1.5 on 2021-04-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0021_auto_20210414_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='track',
            field=models.FileField(upload_to='path/to/audio'),
        ),
    ]
