# Generated by Django 3.1.5 on 2021-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0023_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
