# Generated by Django 3.1.5 on 2021-04-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0024_auto_20210414_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='item',
            name='videoUser',
        ),
    ]
