# Generated by Django 3.1.5 on 2021-04-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0025_auto_20210414_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Video',
        ),
    ]
